# Generated by Django 2.2.5 on 2019-10-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0004_artigo_user_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='user_autor',
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
