# Generated by Django 2.2.5 on 2019-10-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0005_auto_20191023_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.Profile'),
        ),
    ]
