# Generated by Django 2.2.5 on 2019-10-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0006_auto_20191027_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.CharField(max_length=30),
        ),
    ]
