# Generated by Django 2.2.5 on 2019-10-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0007_auto_20191027_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='pdf',
            field=models.FileField(upload_to='artigos/'),
        ),
    ]
