# Generated by Django 2.2.4 on 2019-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190917_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=300, unique=True, verbose_name='E-mail'),
        ),
    ]
