# Generated by Django 2.2.4 on 2019-11-04 20:45

import django.core.validators
from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191023_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid4, help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma', max_length=300, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Informe um nome de usuário válido. Este valor deve conter apenas letras, números e os caracteres: @/./+/-/_ .', 'invalid')], verbose_name='Usuário'),
        ),
    ]
