# Generated by Django 2.2.5 on 2019-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('H', 'high'), ('M', 'mid'), ('L', 'low')], max_length=1)),
            ],
        ),
    ]
